set nobackup
set noswapfile
set autoread
set hidden
set showcmd
set number
set virtualedit=onemore
set smartindent
set showmatch
set laststatus=2
set wildmode=list:longest
set clipboard=unnamedplus

inoremap <c-d> <delete>
inoremap <c-j> <down>
inoremap <c-k> <up>
inoremap <c-h> <left>
inoremap <c-l> <right>
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk

xnoremap p "_dP
xnoremap P "_dP